### PR TITLE
Introducing a php and node build container concept

### PR DESCRIPTION
**Pull request by jlaswell**
Developers now have access to three new artisan commands that can be
used to build dependencies in a reliable way: `builder:all`,
`builder:composer`, and `builder:node`.

Each `builder:*` command calls `docker run` against the php or node
container to install dependencies. This keeps projects using consistent
versions of composer and npm to do package installations across teams
and in CI.

### CODE REVIEW

**Comment by bkuhl** [comment]
It might be valuable to pull this functionality into a small service that we out in it's own container that gets pulled in via docker-compose.  Then it won't be tied to the applications dependencies

**Comment by jlaswell** [comment]
I've added the two builder containers in via docker-compose, but I couldn't define a good way to interact with them without using some form of `docker run -it ...`. The goal is to make it easier for devs to type `php artisan builder:all` than to type `composer install;npm i`.

Are you saying that this could be its own package that we could just add a service provider or command class paths for?

**Comment by jlaswell** [comment]
This may need to be updated based on https://github.com/Realpage/builder/pull/1

**Comment by bkuhl** [comment]
I really like this being a shortcut to working with the containers - good thinking!  

> Are you saying that this could be its own package that we could just add a service provider or command class paths for?
Yes!  This repo is a starting point and if we include this command here and now, it'll be very difficult to publish updates to applications that started here.  If it's a package we can add on to it freely and just tell people to update.

**Comment by jlaswell** [comment]
Good call. You can see progress on the package implementation over at https://github.com/Realpage/builder/pull/1

**Comment by jlaswell** [comment]
This readme will still need to be updated. Just don't want to do it until we're happy with what we've got.

**Comment by jlaswell** [comment]
Pinging this

**Comment by bkuhl** [comment]
This shouldn't be merged as the builder stuff is now in it's own package

**Comment by jlaswell** [comment]
:+1: I'm going to close this PR, and we can try a different approach based on the builder package.

**Pull request closed without merging**
