### PR TITLE
Added phpcs to CI

### PR DESCRIPTION
**Pull request by bkuhl**
Only checking the `app` directory.  Currently the `tests` directory isn't namespaced which is a PSR violation.

### CODE REVIEW

**Comment by bkuhl** [comment]
@millidavids @jlaswell

**Comment by jlaswell** [comment]
This will break usage of [group use declarations](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.group-use-declarations), so we will need to take not if that when developing and possibly add a note to the readme.

**Comment by bkuhl** [comment]
I don't think we'd need to document it, a failing CI build will communicate the issue.

**Comment by jlaswell** [comment]
:+1:

**Pull request merged**
