### PR TITLE
Readme updates

### PR DESCRIPTION
**Pull request by bkuhl**
* Added a list of what's included out of the box with this repo
 * Moved instructions how to get up and running to the CONTRIBUTING.md file

@jlaswell @millidavids

### CODE REVIEW

**Comment by bkuhl** [comment]
:pager:

**Comment by jlaswell** [comment]
LGTM

**Comment by bkuhl** [comment]
Don't forget to delete the branch!

**Comment by jlaswell** [comment]
https://media3.giphy.com/media/3o7WTE87Sn0IwL5STe/200w.gif

**Pull request merged**
